### ISSUE TITLE
Where is streamFlow.h

### ISSUE THREAD

**Issue by jpliew** [neu-rah/AnsiStream#1]
Hey mate, 

Thanks for the library, may I know where is 

https://github.com/neu-rah/AnsiStream/blob/e4f35020fd1a2965cc44e1acf3b95fbc2a99ade7/src/AnsiStream.h#L38

please ? Thanks

**Comment by neu-rah** [comment]
Hi!

good point, i should include the link on readme.md

https://github.com/neu-rah/streamFlow
