### ISSUE TITLE
ambiguous overload for 'operator<<' 

### ISSUE THREAD

**Issue by koendv** [neu-rah/AnsiStream#2]
I'm trying to use ArduinoMenu as ansiSerial, but compilation fails. 
Arduino: 1.8.9 (Mac OS X), Board: "Arduino/Genuino Uno"

In file included from /Users/user/Documents/Arduino/libraries/ArduinoMenu_library/src/menuIO/ansiSerialOut.h:11:0,
                 from /Users/user/Documents/Arduino/libraries/ArduinoMenu_library/examples/Serial/ansiSerial/ansiSerial/ansiSerial.ino:21:
/Users/user/Documents/Arduino/libraries/ArduinoMenu_library/src/AnsiStream.h: In member function 'Print& ANSI::eraseLine::operator()(Print&) const':
/Users/user/Documents/Arduino/libraries/ArduinoMenu_library/src/AnsiStream.h:147:86: error: ambiguous overload for 'operator<<' (operand types are 'Print' and 'char')
  struct eraseLine {inline Print& operator()(Print& out) const {return out<<preamble()<<'2'<<'K';}};
                 
The problem seems to be in AnsiStream: compilation of ansiTest also fails. 

BTW, I'd like to thank you for your menu library. I like that it is small and does not have a lot of overhead.

**Comment by neu-rah** [comment]
Hi!

changed the streaming library to the alternative one to avoid the ambiguity
so, the previous one was https://github.com/neu-rah/streamFlow
alternative https://github.com/scottdky/Streaming

please install the alternative
